//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int Id { get; set; }
        public int Value { get; set; }
        public string Comment { get; set; }
        public int IdStudent { get; set; }
        public int IdLesson { get; set; }
    
        public virtual Lesson Lessons { get; set; }
        public virtual Student Students { get; set; }
    }
}
