//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JournalStorage : DbContext
    {
        public JournalStorage()
            : base("name=JournalStorage")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Discipline> Disciplines { get; set; }
        public virtual DbSet<Grade> Grades1 { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Journal> Journals1 { get; set; }
        public virtual DbSet<Lesson> Lessons1 { get; set; }
        public virtual DbSet<Student> Students1 { get; set; }
        public virtual DbSet<Teacher> Teachers1 { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
