//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public int MainTeacherId { get; set; }
        public int DisciplineId { get; set; }
    
        public virtual Discipline Disciplines { get; set; }
        public virtual Group Groups { get; set; }
        public virtual Teacher Teachers { get; set; }
    }
}
